### ISSUE TITLE
contrail api stdout is not collected

### ISSUE THREAD

**Issue by mnederlof** [salt-formulas/salt-formula-opencontrail#29]
Line https://github.com/salt-formulas/salt-formula-opencontrail/blob/master/opencontrail/meta/heka.yml#L127

should be:
`      file_match: 'contrail/contrail-(?P<Service>(api|discovery)-\d-stdout)\.log\.?(?P<Seq>\d*)$'`

**Comment by ildarsv** [comment]
Hello @mnederlof ! The change was merged, thank you!
https://github.com/salt-formulas/salt-formula-opencontrail/blob/master/opencontrail/meta/heka.yml#L127
